### ISSUE TITLE
how to solve 'ImportError: cannot import name 'crop_and_resize''

### ISSUE THREAD

**Issue by q1nwu** [darolt/mask_rcnn#4]

**Comment by densechen** [comment]
Do you solve this problem? I have met the same question with you .

**Comment by q1nwu** [comment]
Not yet.

**Comment by densechen** [comment]
I have solved this problem. You should mv the build file to corresponding place in models folder, and everything goes well.

**Comment by nguyen14ck** [comment]
@LittleLampChen 
Could you explain how to make it works? Which version of Python and Pytorch do you use?
Mine are:
CentOS 7
Python 3.6.9
Pytorch 1.2
Cuda 9.2

I can run tests in ./test/nms_test.py and ./samples/image_resize_test.py.
However, when I run with: 
```
python ./samples/nuclei.py train
```
There are so many errors with float type like:
```
TypeError: 'float' object is not subscriptable
float type is not iterable
imgaug not support float64 dtype
```

```
   File "samples/nuclei.py", line 90, in <module>
    train(model, dataset_train, dataset_val)
  File "/home/mask_rcnn_pytorch-1.0/mrcnn/actions/train.py", line 28, in train
    model.fit(dataset_train, dataset_val, Config.TRAINING.LEARNING.RATE, Config.TRAINING.NUM_EPOCHS, 'heads', augmentation=augmentation)
  File "/home/mask_rcnn_pytorch-1.0/mrcnn/models/model.py", line 343, in fit
    train_losses = self._train_epoch(train_generator, optimizer)
  File "/home/mask_rcnn_pytorch-1.0/mrcnn/models/model.py", line 367, in _train_epoch
    for step, inputs in enumerate(datagenerator):
  File "/home/anaconda3/envs/pycon/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/anaconda3/envs/pycon/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/anaconda3/envs/pycon/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/pycon/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/envs/pycon/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/pycon/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mask_rcnn_pytorch-1.0/mrcnn/data/data_generator.py", line 259, in __getitem__
    use_mini_mask=Config.MINI_MASK.USE)
  File "/home/mask_rcnn_pytorch-1.0/mrcnn/data/data_generator.py", line 48, in load_image_gt
    image_metas.padding, image_metas.crop)
  File "/home/mask_rcnn_pytorch-1.0/mrcnn/utils/utils.py", line 414, in resize_mask
    mask = scipy.ndimage.zoom(mask, zoom=[scale[0], scale[1], 1], order=0)
TypeError: 'float' object is not subscriptable
```

**Comment by densechen** [comment]
I am using Ubuntu 16.04 to run this code with python 3.6, pytorch 1.2And I think the wrong didn't come from crop_size.&nbsp;
Maybe you can repair this problem by changing the dtype into correct one.




------------------&nbsp;Original&nbsp;------------------

**Comment by nguyen14ck** [comment]
@LittleLampChen 
I did not change the code. Not understand why it has problems with dtype.
Coud you give me an example of the command you used to run file "nuclei.py" successfully? 
And where could I download a pre-trained model to test it?
Many thanks

**Comment by shanniruo** [comment]
@densechen where is the build file?

**Comment by HosseinHassanzadeh** [comment]
> 
> 
> @LittleLampChen
> I did not change the code. Not understand why it has problems with dtype.
> Coud you give me an example of the command you used to run file "nuclei.py" successfully?
> And where could I download a pre-trained model to test it?
> Many thanks

Did you fix it?

**Comment by HosseinHassanzadeh** [comment]
> 
> 
> @LittleLampChen
> I did not change the code. Not understand why it has problems with dtype.
> Coud you give me an example of the command you used to run file "nuclei.py" successfully?
> And where could I download a pre-trained model to test it?
> Many thanks

Did you fix it?
I have the same problem

**Comment by densechen** [comment]
Sorry, I have forgotten the details. But, I think that you should pay attention to this sentence in README.md:
```
for installation instructions, just *export mrcnn directory to PYTHONPATH* and run: python setup.py install
```
@nguyen14ck @shanniruo @HosseinHassanzadeh
